<a href="https://colab.research.google.com/github/ssaurabh053/Data-Science/blob/main/2_Reshape_and_Random_number_generator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.random.rand(3,3)

array([[0.06108708, 0.8263244 , 0.74611124],
       [0.18292794, 0.12044631, 0.88917187],
       [0.60306495, 0.53387507, 0.76381417]])

In [ ]:
arr=np.random.rand(3,3)

In [ ]:
arr

array([[0.40911639, 0.27986413, 0.49664735],
       [0.51789466, 0.1937825 , 0.17299949],
       [0.26145601, 0.1845492 , 0.20487711]])

In [ ]:
arr1 = np.arange(0,11,1)

In [ ]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr2 = np.linspace(0,11,2)

In [ ]:
arr2

array([ 0., 11.])

In [ ]:
arr1.reshape(11,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [ ]:
arr1.reshape(11,1).flatten() # Convert any ndim array to 1 dimensional

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.random.random((3,3))

array([[0.89185528, 0.07049127, 0.62382811],
       [0.08632177, 0.43565582, 0.81078517],
       [0.02989238, 0.45464167, 0.30381795]])