<a href="https://colab.research.google.com/github/ssaurabh053/Data-Science/blob/main/Arithmetic_operations_on_Multiple_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1 =np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2 =np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [ ]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr1 + arr2 ##To perform arithemetic operations on both colum size of 1 st array should be same as row of 2nd

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
arr1 * arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [ ]:
arr3 = np.array([1,2,3])

In [ ]:
arr2 + arr3

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [ ]:
arr2 * arr3

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [ ]:
arr3[0] 

1

In [ ]:
arr2[1:2,1:2]

array([[5]])

In [ ]:
arr2[1,1]

5