<a href="https://colab.research.google.com/github/ssaurabh053/Data-Science/blob/main/Arithmetic_operations_on_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5])

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr + 1 ##Arithmetic opertion in this will operate on each element

array([2, 3, 4, 5, 6])

In [ ]:
arr * 5

array([ 5, 10, 15, 20, 25])

In [ ]:
arr - 1

array([0, 1, 2, 3, 4])

In [ ]:
arr / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
arr ** 2

array([ 1,  4,  9, 16, 25])

In [ ]:
arr+= 1

In [ ]:
arr

array([2, 3, 4, 5, 6])

In [ ]:
arr.max()

6

In [ ]:
arr.min()

2

In [ ]:
arr.sum()

20

In [ ]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr1.max(axis=0) #Max column wise for 2d array

array([7, 8, 9])

In [ ]:
arr1.max(axis=1) #Max row wise for 2d array

array([3, 6, 9])

In [ ]:
arr1.min(axis=0) #Min column wise for 2d array

array([1, 2, 3])

In [ ]:
arr1.min(axis=1) #Min row wise for 2d array

array([1, 4, 7])

In [ ]:
arr1.sum()

45