<a href="https://colab.research.google.com/github/ssaurabh053/Data-Science/blob/main/Array_Merging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])

In [ ]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr2 = np.array([[9,8,7,6],[5,4,3,2]])

In [ ]:
arr2

array([[9, 8, 7, 6],
       [5, 4, 3, 2]])

In [ ]:
np.vstack((arr1,arr2)) #Order of the array provided in the input matters

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6],
       [5, 4, 3, 2]])

In [ ]:
np.hstack((arr1,arr2))

array([[1, 2, 3, 4, 9, 8, 7, 6],
       [5, 6, 7, 8, 5, 4, 3, 2]])

In [ ]:
arr = np.concatenate((arr1,arr2),axis=0) #Column wise

In [ ]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6],
       [5, 4, 3, 2]])

In [ ]:
np.concatenate((arr1,arr2),axis=1) #Row wise

array([[1, 2, 3, 4, 9, 8, 7, 6],
       [5, 6, 7, 8, 5, 4, 3, 2]])

In [ ]:
np.hsplit(arr,2)

[array([[1, 2],
        [5, 6],
        [9, 8],
        [5, 4]]), array([[3, 4],
        [7, 8],
        [7, 6],
        [3, 2]])]

In [ ]:
np.vsplit(arr,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[9, 8, 7, 6],
        [5, 4, 3, 2]])]