<a href="https://colab.research.google.com/github/ssaurabh053/Data-Science/blob/main/Array_Sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.sort(arr,axis=0,kind='mergesort')

array([[1, 2, 3, 5, 2],
       [1, 3, 4, 6, 7],
       [9, 5, 4, 6, 8]])

In [ ]:
arr=np.array([[1,2,3,5,8],
          [9,5,4,6,7],
          [1,3,4,6,2]])

In [ ]:
np.sort(arr,axis=1,kind='mergesort') #Row wise

array([[1, 2, 3, 5, 8],
       [4, 5, 6, 7, 9],
       [1, 2, 3, 4, 6]])

In [ ]:
arr

array([[1, 2, 3, 5, 8],
       [9, 5, 4, 6, 7],
       [1, 3, 4, 6, 2]])

In [ ]:
np.sort(arr,axis=0,kind='quick')

array([[1, 2, 3, 5, 2],
       [1, 3, 4, 6, 7],
       [9, 5, 4, 6, 8]])

In [ ]:
np.sort(arr,axis=0,kind='heap')

array([[1, 2, 3, 5, 2],
       [1, 3, 4, 6, 7],
       [9, 5, 4, 6, 8]])

In [ ]:
np.sort(arr,axis=0,kind='stable')

array([[1, 2, 3, 5, 2],
       [1, 3, 4, 6, 7],
       [9, 5, 4, 6, 8]])