<a href="https://colab.research.google.com/github/ssaurabh053/Data-Science/blob/main/Array_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8])

In [ ]:
arr[0]

1

In [ ]:
arr[1:3]

array([2, 3])

In [ ]:
arr1=np.array([[1,2,3,4,5,6,7,8],[9,8,7,5,6,4,3,3]])

In [ ]:
arr1

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [9, 8, 7, 5, 6, 4, 3, 3]])

In [ ]:
arr1 [ : , 3:5]

array([[4, 5],
       [5, 6]])

In [ ]:
arr1 [ 0  , 3:5]

array([4, 5])